<img src="../images/logo_VORTEX.png" width="200" height="auto" alt="Company Logo">

| Project| Authors           | Company                                 | Year | Chapter |
|--------|-------------------|-----------------------------------------|------|---------|
| Pywind | Oriol L & Arnau T | [Vortex FdC](https://www.vortexfdc.com) | 2025 | 1       |

# Chapter 1: Loading NetCDF

_Overview:_

This script reads meteorological **NetCDF data (.nc)** and uses functions to load and show the file structure and a quick overview.

> What are *NetCDF* files? Read our Blog post [here](https://vortexfdc.com/blog/what-is-a-netcdf-file/).

- Measurements (NetCDF) - Contains single height with limited variables.
- Vortex NetCDF - NetCDF file format with multiple heights and variables.

_Data Storage:_

The acquired data is stored in two data structures for comparison and analysis:
- Xarray Dataset
- Pandas DataFrame

_Objective:_

- To understand the variance in data storage when using Xarray and Pandas.
- Utilize the basic commands to make a quick overview of the loaded data; e.g. `describe()` and `head()`.
_Data:_
Data used in this chapter is explaned and can be download from the [data sample documentation](README_about_datasets.md)



### Import Libraries



In [5]:
import xarray as xr
import numpy as np
import pandas as pd
import os


### Define Paths and Site


In [6]:
SITE = 'froya'
pwd = os.getcwd()
base_path = os.path.join(pwd, '../data')

measurements_netcdf = os.path.join(base_path, f'{SITE}/measurements/obs.nc')
vortex_netcdf = os.path.join(base_path, f'{SITE}/vortex/SERIE/vortex.serie.era5.utc0.nc')

print(f'Measurements NetCDF: {measurements_netcdf}')
print(f'Vortex NetCDF: {vortex_netcdf}')

Measurements NetCDF: /home/oriol/vortex/git/pywind_private/notebooks/../data/froya/measurements/obs.nc
Vortex NetCDF: /home/oriol/vortex/git/pywind_private/notebooks/../data/froya/vortex/SERIE/vortex.serie.era5.utc0.nc


### Read NetCDF functions


In [7]:
# Read measurements NetCDF
ds_measurements = xr.open_dataset(measurements_netcdf)
ds_measurements

<xarray.Dataset> Size: 15MB
Dimensions:  (lat: 1, lon: 1, lev: 5, time: 171895)
Coordinates:
  * lat      (lat) float64 8B 63.67
  * lon      (lon) float64 8B 8.343
  * lev      (lev) float64 40B 10.0 25.0 40.0 70.0 100.0
  * time     (time) datetime64[ns] 1MB 2009-11-18T13:50:00 ... 2014-12-07T07:...
Data variables:
    M        (lat, lon, lev, time) float64 7MB ...
    Dir      (lat, lon, lev, time) float64 7MB ...
Attributes:
    description:  Wind Speed (module velocity)
    long_name:    Wind speed
    units:        m/s
    lag:          -7

In [8]:
# Read Vortex NetCDF
ds_vortex = xr.open_dataset(vortex_netcdf)
ds_vortex

<xarray.Dataset> Size: 58MB
Dimensions:  (lon: 1, lat: 1, lev: 10, time: 176424)
Coordinates:
  * lon      (lon) float32 4B 8.342
  * lat      (lat) float32 4B 63.67
  * lev      (lev) float32 40B 8.0 28.0 52.0 80.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 1MB 2004-01-01 ... 2024-02-15T23:00:00
Data variables:
    M        (lev, time, lat, lon) float32 7MB ...
    Dir      (lev, time, lat, lon) float32 7MB ...
    T        (lev, time, lat, lon) float32 7MB ...
    D        (lev, time, lat, lon) float32 7MB ...
    P        (lev, time, lat, lon) float32 7MB ...
    RH       (lev, time, lat, lon) float32 7MB ...
    RI       (time, lev, lat, lon) float64 14MB ...
Attributes:
    Reanalysis:            ERA5
    Origin:                VORTEX SL
    Product:               SERIES
    HorizontalResolution:  3km
    Produced:              2024-04-11 11:09:26
    WorkID:                1235817
    history:               Vortex processed time serie from era5-wrf downscal...
    NCO:                   netCDF Operators version 5.0.6 (Homepage = http://...

We can observe the typical structure of **Xarray** data. When multiple variables are present, it is referred to as a *Dataset*. If there is only a single variable, it is called a *DataArray*. 

>Let's explore the various information available within these structures.

In [9]:
# Dataset coordinates
ds_vortex.coords

Coordinates:
  * lon      (lon) float32 4B 8.342
  * lat      (lat) float32 4B 63.67
  * lev      (lev) float32 40B 8.0 28.0 52.0 80.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 1MB 2004-01-01 ... 2024-02-15T23:00:00

In [10]:
# Dataset dimensions
ds_vortex.dims

FrozenMappingWarningOnValuesAccess({'lon': 1, 'lat': 1, 'lev': 10, 'time': 176424})

The **metadata** is called *attributes*. It is a dictionary in Python.

In [11]:
# Dataset attributes
ds_vortex.attrs

{'Reanalysis': 'ERA5',
 'Origin': 'VORTEX SL',
 'Product': 'SERIES',
 'HorizontalResolution': '3km',
 'Produced': '2024-04-11 11:09:26',
 'WorkID': np.int32(1235817),
 'history': 'Vortex processed time serie from era5-wrf downscalling',
 'NCO': 'netCDF Operators version 5.0.6 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)'}

And the data variables with its dimensions and data type.

In [12]:
ds_vortex.data_vars

Data variables:
    M        (lev, time, lat, lon) float32 7MB ...
    Dir      (lev, time, lat, lon) float32 7MB ...
    T        (lev, time, lat, lon) float32 7MB ...
    D        (lev, time, lat, lon) float32 7MB ...
    P        (lev, time, lat, lon) float32 7MB ...
    RH       (lev, time, lat, lon) float32 7MB ...
    RI       (time, lev, lat, lon) float64 14MB ...

Each var has attributes, with metadata information.

In [13]:
ds_vortex.variables['M'].attrs

{'description': 'Wind Speed (module velocity)',
 'long_name': 'Wind speed',
 'units': 'm/s'}

The data for each variable can also be accessed individually, retaining the associated coordinates and attributes. Each variable may have different dimensions and corresponding coordinates

In [14]:
ds_vortex['M']

<xarray.DataArray 'M' (lev: 10, time: 176424, lat: 1, lon: 1)> Size: 7MB
[1764240 values with dtype=float32]
Coordinates:
  * lon      (lon) float32 4B 8.342
  * lat      (lat) float32 4B 63.67
  * lev      (lev) float32 40B 8.0 28.0 52.0 80.0 ... 182.0 220.0 263.0 330.0
  * time     (time) datetime64[ns] 1MB 2004-01-01 ... 2024-02-15T23:00:00
Attributes:
    description:  Wind Speed (module velocity)
    long_name:    Wind speed
    units:        m/s

We have a DataArray when dealing with a single 'column' of data.

In [16]:
type(ds_vortex['M'])

xarray.core.dataarray.DataArray

To get just the values in a Numpy Array format. This is what we would say a common array.

In [17]:
type(ds_vortex['M'].values)

numpy.ndarray

In [18]:
ds_vortex['M'].values

array([[[[ 4.4713726]],

        [[ 4.1169853]],

        [[ 4.61843  ]],

        ...,

        [[ 6.359386 ]],

        [[ 5.7004547]],

        [[ 4.4155455]]],


       [[[ 4.538038 ]],

        [[ 4.203529 ]],

        [[ 4.7278867]],

        ...,

        [[ 6.6354218]],

        [[ 5.8938055]],

        [[ 4.5033   ]]],


       [[[ 4.553902 ]],

        [[ 4.244887 ]],

        [[ 4.783167 ]],

        ...,

        [[ 6.721409 ]],

        [[ 5.9447217]],

        [[ 4.5229263]]],


       ...,


       [[[ 7.634639 ]],

        [[ 6.5912933]],

        [[ 7.0861382]],

        ...,

        [[ 6.487186 ]],

        [[ 4.5752106]],

        [[ 3.7386734]]],


       [[[10.105934 ]],

        [[ 9.102782 ]],

        [[ 9.344037 ]],

        ...,

        [[ 5.3326015]],

        [[ 3.9022276]],

        [[ 4.1259403]]],


       [[[ 9.446582 ]],

        [[ 9.830642 ]],

        [[ 9.356058 ]],

        ...,

        [[ 3.5960932]],

        [[ 3.0247219]],

        [[ 3.6984

The array still has some dimensions. We can remove single value dimensions using the squeeze() call for the object. See how it converts after aplying it.

In [19]:
print(ds_vortex['M'].shape)
print(ds_vortex['M'].squeeze().values)
print(ds_vortex['M'].squeeze().shape)


(10, 176424, 1, 1)
[[ 4.4713726  4.1169853  4.61843   ...  6.359386   5.7004547  4.4155455]
 [ 4.538038   4.203529   4.7278867 ...  6.6354218  5.8938055  4.5033   ]
 [ 4.553902   4.244887   4.783167  ...  6.721409   5.9447217  4.5229263]
 ...
 [ 7.634639   6.5912933  7.0861382 ...  6.487186   4.5752106  3.7386734]
 [10.105934   9.102782   9.344037  ...  5.3326015  3.9022276  4.1259403]
 [ 9.446582   9.830642   9.356058  ...  3.5960932  3.0247219  3.6984565]]
(10, 176424)


We can access to the values refering by each dimension indexes. ":" refers to start:end considering all in this case. You can use indexes before and after the ":".
In this case we access:
- first 24 values for the 0 level.(one day time series at lev=0)
- first value of all levels. (shear at this timestamp)

In [20]:
print(ds_vortex['M'].squeeze().values[0:12,0])
print(ds_vortex['M'].squeeze().values[0,:])


[ 4.4713726  4.538038   4.553902   4.5563645  4.566679   4.565929
  5.3193936  7.634639  10.105934   9.446582 ]
[4.4713726 4.1169853 4.61843   ... 6.359386  5.7004547 4.4155455]


### Convert to Pandas DataFrame and inspect

Pandas function `head()` shows the first values.

In [21]:
df_measurements = ds_measurements.to_dataframe()
print(type(df_measurements))
df_measurements.head()

<class 'pandas.core.frame.DataFrame'>


M    Dir
lat      lon     lev  time                             
63.66638 8.34251 10.0 2009-11-18 13:50:00  2.560  111.5
                      2009-11-18 14:00:00  2.943   99.5
                      2009-11-18 14:10:00  3.125   91.5
                      2009-11-18 14:20:00  3.654   89.0
                      2009-11-18 14:30:00  3.628   93.5

In [22]:
df_vortex = ds_vortex.to_dataframe()
df_vortex.head()

M         Dir         T  \
lon      lat       lev time                                                  
8.342499 63.666386 8.0 2004-01-01 00:00:00  4.471373  149.532516 -0.700592   
                       2004-01-01 01:00:00  4.116985  158.352905 -0.560852   
                       2004-01-01 02:00:00  4.618430  164.658569 -0.550995   
                       2004-01-01 03:00:00  4.449509  153.565109 -0.627899   
                       2004-01-01 04:00:00  4.555139  141.756287 -0.690002   

                                              D    P   RH   RI  
lon      lat       lev time                                     
8.342499 63.666386 8.0 2004-01-01 00:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 01:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 02:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 03:00:00  0.0  0.0  0.0  0.0  
                       2004-01-01 04:00:00  0.0  0.0  0.0  0.0

### Interpolate to the same height

We have multiple levels in `ds_vortex`, so we need to interpolate the data to match the height levels in `ds_measurements`.

In [23]:
max_height = ds_measurements.squeeze().coords['lev'].max().values
print(f'Max height in measurements = {max_height}')

Max height in measurements = 100.0


In [24]:
ds_vortex = ds_vortex.interp(lev=max_height)
ds_vortex

<xarray.Dataset> Size: 11MB
Dimensions:  (lon: 1, lat: 1, time: 176424)
Coordinates:
  * lon      (lon) float32 4B 8.342
  * lat      (lat) float32 4B 63.67
  * time     (time) datetime64[ns] 1MB 2004-01-01 ... 2024-02-15T23:00:00
    lev      float64 8B 100.0
Data variables:
    M        (time, lat, lon) float64 1MB 4.563 4.306 4.867 ... 5.965 4.472
    Dir      (time, lat, lon) float64 1MB 153.9 161.8 166.3 ... 113.3 122.2
    T        (time, lat, lon) float64 1MB -1.842 -1.707 -1.709 ... 0.3004 0.2648
    D        (time, lat, lon) float64 1MB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    P        (time, lat, lon) float64 1MB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    RH       (time, lat, lon) float64 1MB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    RI       (time, lat, lon) float64 1MB 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
Attributes:
    Reanalysis:            ERA5
    Origin:                VORTEX SL
    Product:               SERIES
    HorizontalResolution:  3km
    Produced:              2024-04-11 11:09:26
    WorkID:                1235817
    history:               Vortex processed time serie from era5-wrf downscal...
    NCO:                   netCDF Operators version 5.0.6 (Homepage = http://...

Although the coordinate **lev** is still available, it is no longer a dimension for any variable. (Check for missing *lev in the coordinates.)

### Now we can compare statistics for M and Dir

In [25]:
# Rename direction coordinate
if 'Dir' not in ds_vortex.data_vars and 'D' in ds_vortex.data_vars:
    ds_vortex = ds_vortex.rename({'D':'Dir'})
    
# Drop coordinates lat  and lon  and dimensions of ds_vortex
ds_vortex = ds_vortex.squeeze().reset_coords(drop=True)
ds_measurements = ds_measurements.squeeze().reset_coords(drop=True)

Notebooks allow for a better display format:

In [33]:
from IPython.display import display
display(ds_vortex[['M', 'Dir']].to_dataframe().describe())
display(ds_measurements[['M', 'Dir']].to_dataframe().describe())

M            Dir
count  179040.000000  179040.000000
mean        6.413742     198.042601
std         2.794355      91.595051
min         0.000000       0.000000
25%         4.400000     120.200000
50%         6.360000     219.600000
75%         8.160000     271.000000
max        22.320000     360.000000

M           Dir
count  6.915876e+06  2.303561e+06
mean   4.860977e+00  1.929087e+02
std    2.442716e+00  9.119527e+01
min    0.000000e+00  0.000000e+00
25%    3.030000e+00  1.130000e+02
50%    4.590000e+00  2.130000e+02
75%    6.360000e+00  2.670000e+02
max    2.658000e+01  3.590000e+02

### Thank you for completing this Notebook! 
### *Other references available upon request.*

You now can:

- Open NetCdf using **Xarray** python library.
- Inspect the metadata.
- Rename variables.
- Interpolate within a dimension.
- Convert to **Pandas** DataFrames.
- Have a quick overview of the data using `head()` and `describe()` Pandas functions.

**Don't hesitate to [contact us](https://vortexfdc.com/contact/) for any questions and information.**

## Change Log


| Date (YYYY-MM-DD) | Version | Changed By | Change Description                         |
|-------------------|---------|------------|--------------------------------------------|
| 2023-02-25        | 0.0     | Oriol      | Notebook creation                          |
| 2023-09-28        | 0.2     | Arnau      | Comment sections & add complementary plots |
| 2023-10-02        | 0.3     | Arnau      | Improve notebook visualization             |
| 2024-02-06        | 0.4     | Oriol      | Vortexpy compatibility                     |
| 2024-11-12        | 0.4.1   | Oriol      | Review                                     |


<hr>

## <h3 align="center"> © Vortex F.d.C. 2024. All rights reserved. <h3/>